[build]
publish = "/home/will/projects/netlify-feature-tour/dist"
publishOrigin = "ui"
commandOrigin = "ui"
command = "npm run build"
functions = "/home/will/projects/netlify-feature-tour/netlify/functions"
